### ISSUE TITLE
Lock-screen password prompt color

### ISSUE THREAD

**Issue by rafabs97** [Jannomag/Yaru-Colors#95]
Hi. Using ubuntu 20.04.2, even after applying GDM theme, lock-screen (the one where you enter your password after suspend) is still using original ubuntu orange on the text-box border. Maybe I'm missing something? Thanks in advance.

**Comment by Jannomag** [comment]
Did you reboot?

**Comment by rafabs97** [comment]
Sorry for not answering before: yes I did, and it keeps happening.

**Comment by Jannomag** [comment]
I started the work on 21.04 theme. Maybe it gets fixed with this. Because of the huge lack of time I’m not able to rework or fix bugs of older versions because every new update of Yaru brings many tiny changes with it. This causes that I need to rework everything step by step which is very time consuming

**Comment by Jannomag** [comment]
I updated the theme to 21.04 (pre-release). You can try it with those files.

Clone the repo, install the theme and then follow the gdm3 instructions in the readme. It should also work on 20.04.

**Comment by rafabs97** [comment]
Sorry for the late answer. I haven't used Ubuntu in a long, long time. Now I've returned to use the distro, and installed your awesome theme again. As far as I've been able to test, the error still exists. Maybe it's just a thing of 20.04 LTS (I try to stick to LTS versions for stability reasons); however, it is not something really distracting, so I guess it's not a priority :) Awesome theme overall, the best fitting I've found yet.
