### ISSUE TITLE
syslog error

### ISSUE THREAD

**Issue by sanwablo** [Jannomag/Yaru-Colors#97]
I'm getting the following error repeatedly with Yaru-Dark, which is bloating my syslog files:

`Theme parsing error: gtk.css:5449:34: Invalid name of pseudo-class`

Is there any way to fix this?

**Comment by Jannomag** [comment]
Which distro and version are you using and what theme do you use exactly?

**Comment by sanwablo** [comment]
Hey @Jannomag! I'm using Yaru-Dark Pink on Ubuntu 20.04.

**Comment by Jannomag** [comment]
It can be related with this: https://github.com/ubuntu/yaru/issues/2207

Yaru updated it, so it should be fixed with my lates 21.04 commit, which should also work fine with 20.04.
I won't fix it in older versions because it's too much work to compile everything from scratch and keep it archived.

So try my latest commit (via clone, I didn't make a release, yet)

**Comment by Jannomag** [comment]
Did you try with my latest 21.04 release?

**Comment by sanwablo** [comment]
Yes, it fixed most of the issue. The log message still appears for some snap packages, like zotero.
